### ISSUE TITLE
"not a valid cookie data" stops the parser just due to empty value

### ISSUE THREAD

**Issue by ReeganExE** [aki237/nscjar#2]
Hi,

The cookie value may be an empty string. It's acceptable and is still valid.
The current implementation gets error when the cookie value be empty. I don't think it's correct.
https://github.com/aki237/nscjar/blob/e2df936ddd6050d30dd90c7214c02b5019c42f06/nscjar.go#L129-L131

**Comment by aki237** [comment]
Thanks for creating the issue, Seems like a trivial fix. Can you send a PR?

**Comment by aki237** [comment]
Have fixed this in the latest commit
